# Generated by Django 4.1.2 on 2023-03-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=50)),
                ('reference', models.CharField(default='none', max_length=50)),
                ('description', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=100)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.person')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Services.servicetype')),
            ],
        ),
    ]
