# Generated by Django 4.1.2 on 2023-03-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='latitude_x',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude_y',
            field=models.FloatField(default=0, null=True),
        ),
    ]
