# Generated by Django 4.1.2 on 2023-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_service_latitude_x_service_longitude_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
    ]
