# Generated by Django 4.1.2 on 2023-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_service_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='distance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
