# Generated by Django 4.1.2 on 2023-03-24 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 17, 54, 13673))),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.topic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.person')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 17, 54, 13673))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.person')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sno', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 17, 54, 13673))),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Community.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.person')),
            ],
        ),
    ]
