# Generated by Django 4.1.2 on 2023-03-24 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 21, 7, 990268)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 21, 7, 990268)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 0, 21, 7, 990268)),
        ),
    ]
