# Generated by Django 4.1.2 on 2023-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_alter_comment_time_stamp_alter_likes_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
