# Generated by Django 4.1.2 on 2023-03-24 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0011_alter_comment_time_stamp_alter_likes_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 3, 51, 46, 616350)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 3, 51, 46, 616350)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 3, 51, 46, 616350)),
        ),
    ]
