# Generated by Django 4.1.2 on 2023-03-24 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0012_alter_comment_time_stamp_alter_likes_time_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 5, 22, 59, 214831)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 5, 22, 59, 214831)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 5, 22, 59, 214831)),
        ),
    ]
