# Generated by Django 4.1.2 on 2023-03-25 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('img', models.ImageField(default='None', null=True, upload_to='Profile/ProfileImages/')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', null=True)),
                ('type', models.TextField(choices=[('user', 'user'), ('expert', 'expert'), ('service provider', 'service provider'), ('admin', 'admin')], default='user')),
                ('active', models.BooleanField(default=False)),
                ('latitute_x', models.FloatField(default=0, null=True)),
                ('longitude_y', models.FloatField(default=0, null=True)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
