# Generated by Django 4.1.2 on 2023-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(default='None', null=True, upload_to='static/Profile/'),
        ),
    ]
