# Generated by Django 4.1.2 on 2023-03-24 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0002_alter_chat_thread_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 1, 19, 55, 363565)),
        ),
        migrations.AlterField(
            model_name='chat_thread',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 1, 19, 55, 362540)),
        ),
    ]
