# Generated by Django 4.1.2 on 2023-03-24 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0003_remove_message_time_stamp_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_thread',
            name='last_message',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 1, 52, 57, 911922)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 1, 52, 57, 911922)),
        ),
    ]
