# Generated by Django 4.1.7 on 2023-03-26 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(default='', null=True)),
                ('receiver', models.TextField(default='Buddy', null=True)),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2023, 3, 26, 5, 49, 48, 871553))),
            ],
        ),
    ]
